### ISSUE TITLE
Convert to .net core

### ISSUE THREAD

**Issue by CodyBatt** [petrsnd/Cfa533Rs232#7]
There's nothing special about this project. It should be converted to core.

**Comment by petrsnd** [comment]
@CodyBatt 
Started on it.  Just need to find my device to run the test tool and demo tool on to verify that everything is still happy.
https://github.com/petrsnd/Cfa533Rs232/tree/dotnet-upgrade

The main reason for delaying the port to .NET Standard was System.IO.Ports.SerialPort.  However, Microsoft remedied that years ago with the Windows Compatibility Pack (https://devblogs.microsoft.com/dotnet/announcing-the-windows-compatibility-pack-for-net-core/).  I just never came back to it,. because we only needed .NET Framework for our project.
